import React from "react";
import { Box, Text } from '@chakra-ui/react';

function Timeline() {
    return (
        <Box borderWidth='2px' borderRadius='lg' maxHeight="70vh" overflowY="scroll" padding="5" display={['none', 'none', 'flex']}>
            <Text>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae tempus quam pellentesque nec nam aliquam sem et. Vulputate mi sit amet mauris commodo quis imperdiet massa. Sed ullamcorper morbi tincidunt ornare massa eget egestas. Ac auctor augue mauris augue neque. Tempus egestas sed sed risus pretium quam vulputate. Aenean et tortor at risus viverra adipiscing. Vulputate ut pharetra sit amet. Pellentesque dignissim enim sit amet. Tellus cras adipiscing enim eu turpis egestas.

                Mi sit amet mauris commodo quis imperdiet massa. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Nam at lectus urna duis convallis convallis tellus id. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Felis bibendum ut tristique et egestas quis ipsum. Praesent elementum facilisis leo vel. Cras semper auctor neque vitae tempus. Ultrices tincidunt arcu non sodales neque. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Mattis pellentesque id nibh tortor id aliquet. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Neque sodales ut etiam sit amet. Mauris commodo quis imperdiet massa tincidunt nunc.

                Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Imperdiet dui accumsan sit amet nulla facilisi morbi. Id eu nisl nunc mi ipsum. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Praesent tristique magna sit amet. Vitae elementum curabitur vitae nunc sed velit dignissim. Elementum integer enim neque volutpat ac tincidunt vitae. Massa sed elementum tempus egestas sed sed risus. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Nulla at volutpat diam ut venenatis tellus. Sed felis eget velit aliquet sagittis. Donec massa sapien faucibus et molestie ac feugiat sed. Duis ut diam quam nulla porttitor.

                Pulvinar sapien et ligula ullamcorper. Neque sodales ut etiam sit amet nisl purus. Sed velit dignissim sodales ut eu sem integer vitae justo. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Ut placerat orci nulla pellentesque dignissim enim sit. Quam id leo in vitae turpis massa sed elementum tempus. Ullamcorper a lacus vestibulum sed arcu. Massa eget egestas purus viverra. Natoque penatibus et magnis dis parturient montes. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Id cursus metus aliquam eleifend. Sapien eget mi proin sed libero enim sed.

                Lobortis mattis aliquam faucibus purus in. Faucibus in ornare quam viverra orci sagittis eu. Egestas sed sed risus pretium quam vulputate dignissim suspendisse. A scelerisque purus semper eget duis at tellus at. Urna nunc id cursus metus aliquam eleifend mi. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Massa ultricies mi quis hendrerit dolor magna eget. Tristique sollicitudin nibh sit amet. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Metus vulputate eu scelerisque felis imperdiet proin. Arcu odio ut sem nulla pharetra diam sit amet nisl. Erat imperdiet sed euismod nisi porta lorem. Etiam sit amet nisl purus in mollis. Sociis natoque penatibus et magnis dis. Cursus euismod quis viverra nibh cras. Massa ultricies mi quis hendrerit dolor magna eget est lorem. Nunc sed id semper risus in hendrerit gravida rutrum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae tempus quam pellentesque nec nam aliquam sem et. Vulputate mi sit amet mauris commodo quis imperdiet massa. Sed ullamcorper morbi tincidunt ornare massa eget egestas. Ac auctor augue mauris augue neque. Tempus egestas sed sed risus pretium quam vulputate. Aenean et tortor at risus viverra adipiscing. Vulputate ut pharetra sit amet. Pellentesque dignissim enim sit amet. Tellus cras adipiscing enim eu turpis egestas.

                Mi sit amet mauris commodo quis imperdiet massa. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Nam at lectus urna duis convallis convallis tellus id. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Felis bibendum ut tristique et egestas quis ipsum. Praesent elementum facilisis leo vel. Cras semper auctor neque vitae tempus. Ultrices tincidunt arcu non sodales neque. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Mattis pellentesque id nibh tortor id aliquet. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Neque sodales ut etiam sit amet. Mauris commodo quis imperdiet massa tincidunt nunc.

                Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Imperdiet dui accumsan sit amet nulla facilisi morbi. Id eu nisl nunc mi ipsum. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Praesent tristique magna sit amet. Vitae elementum curabitur vitae nunc sed velit dignissim. Elementum integer enim neque volutpat ac tincidunt vitae. Massa sed elementum tempus egestas sed sed risus. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Nulla at volutpat diam ut venenatis tellus. Sed felis eget velit aliquet sagittis. Donec massa sapien faucibus et molestie ac feugiat sed. Duis ut diam quam nulla porttitor.

                Pulvinar sapien et ligula ullamcorper. Neque sodales ut etiam sit amet nisl purus. Sed velit dignissim sodales ut eu sem integer vitae justo. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Ut placerat orci nulla pellentesque dignissim enim sit. Quam id leo in vitae turpis massa sed elementum tempus. Ullamcorper a lacus vestibulum sed arcu. Massa eget egestas purus viverra. Natoque penatibus et magnis dis parturient montes. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Id cursus metus aliquam eleifend. Sapien eget mi proin sed libero enim sed.

                Lobortis mattis aliquam faucibus purus in. Faucibus in ornare quam viverra orci sagittis eu. Egestas sed sed risus pretium quam vulputate dignissim suspendisse. A scelerisque purus semper eget duis at tellus at. Urna nunc id cursus metus aliquam eleifend mi. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Massa ultricies mi quis hendrerit dolor magna eget. Tristique sollicitudin nibh sit amet. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Metus vulputate eu scelerisque felis imperdiet proin. Arcu odio ut sem nulla pharetra diam sit amet nisl. Erat imperdiet sed euismod nisi porta lorem. Etiam sit amet nisl purus in mollis. Sociis natoque penatibus et magnis dis. Cursus euismod quis viverra nibh cras. Massa ultricies mi quis hendrerit dolor magna eget est lorem. Nunc sed id semper risus in hendrerit gravida rutrum.
            </Text>
        </Box>
    );
}

export default Timeline;